### ISSUE TITLE
Use glue-core Python API for parsing the .glue file content?

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/glue-lab#18]
Instead of custom reading of `this._model.contents`

**Comment by jfoster17** [comment]
Is this something you could use some help with? I'll admit that the code for `GlueSerializer` and `GlueUnSerializer` is not the most beginner-friendly, but it does work and I don't want to have a lot of wasted effort re-inventing this.

**Comment by martinRenou** [comment]
Thanks for commenting. 

Reading the .glue file with the glue-core API was one of the things we considered doing, but [this PR](https://github.com/QuantStack/glue-lab/pull/48) will be the approach we'll take instead: having the glue-jupyter application (Python side) be connected to the same shared model as the front-end.
