### ISSUE TITLE
Scatter viewers don't show up at load

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/glue-lab#24]
Scatter viewers (more specifically the bqplot plot content) do not show up until there is an interaction via selection.

This may be bqplot waiting for an event that never comes (after-attach?)

**Comment by hbcarlos** [comment]
Probably, because it happens in the notebook as well.

**Comment by martinRenou** [comment]
Just to clarify, you mean the classic Notebook?

**Comment by hbcarlos** [comment]
No. JupyterLab's notebook using glue-jupyter with the following example (I used the data from this repository):

```
import glue_jupyter as gj
app = gj.jglue()
data_image = app.load_data('w5.fits')

scatter = app.scatter2d(data=data_image)
```

**Comment by hbcarlos** [comment]
In Jupyterlab v3.6

**Comment by martinRenou** [comment]
Ok, thanks for trying! I'll have a look into this one, if you're not already on it.

**Comment by martinRenou** [comment]
Closing and replaced by https://github.com/glue-viz/glue-jupyter/issues/353
